[package]
name = "arisama"
version = "0.1.0"
authors = ["shinichi kogai <kogai0121@gmail.com>"]

[dependencies]
dotenv = "0.10.0"
iron = "0.5.1"
router = "0.5.1"
iron-sessionstorage = "0.6.6"
urlencoded = "0.5.0"
mount = "0.3.0"
serde_json = "0.9"
iron-test = "0.5.0"